---
- name: Ensure apt key for docker is present.
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg
    state: present
  become: true
  when: install_docker

- name: Ensure repository for docker is present.
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ ansible_lsb.codename }} stable
    state: present
  become: true
  when: install_docker

- name: Ensure docker and docker tools are present.
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
  become: true
  when: install_docker

- name: Ensure the current user is part of docker group.
  ansible.builtin.user:
    name: "{{ ansible_user|default(lookup('env', 'USER')) }}"
    groups: docker
    append: true
  become: true

- name: Ensure the docker service is enabled and started.
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  when: install_docker
